man: 'Маслов Алексей Александрович'
istina_people: 'https://istina.msu.ru/profile/Amaslov/'
news_wrang:
    - 'https://lenta.ru/news/2022/07/02/masloved/'
    - 'https://msk1.ru/text/world/2022/10/11/71727275/'
    - 'https://newizv-ru.turbopages.org/newizv.ru/s/news/incident/26-08-2021/smi-millioner-iz-truschob-artem-maslov-prigovoren-k-10-godam-v-oae'
    - 'https://www.rbc.ru/rbcfreenews/61b60da39a794770a69643ea'
    - 'https://lenta.ru/news/2019/01/21/bureya/'
news_truth:
    - 'https://lenta.ru/news/2022/05/26/maslov/'
    - 'https://lenta.ru/news/2022/10/11/taivan/'
    - 'https://lenta.ru/news/2022/05/26/maslov/'
    - 'https://mir24-tv.turbopages.org/mir24.tv/s/news/16527090/professor-mgu-obyasnil-pochemu-svmda-stanovitsya-centrom-prinyatiya-reshenii'