name: 'Маслов Алексей Александрович'
istina_people: 'https://istina.msu.ru/profile/Amaslov/'
news:
    - ['https://lenta.ru/news/2022/07/02/masloved/', 0]
    - ['https://msk1.ru/text/world/2022/10/11/71727275/', 0]
    - ['https://newizv-ru.turbopages.org/newizv.ru/s/news/incident/26-08-2021/smi-millioner-iz-truschob-artem-maslov-prigovoren-k-10-godam-v-oae', 0]
    - ['https://www.rbc.ru/rbcfreenews/61b60da39a794770a69643ea', 0]
    - ['https://lenta.ru/news/2019/01/21/bureya/', 0]
    - ['https://lenta.ru/news/2022/05/26/maslov/', 1]
    - ['https://lenta.ru/news/2022/10/11/taivan/', 1]
    - ['https://lenta.ru/news/2022/05/26/maslov/', 1]
    - ['https://mir24-tv.turbopages.org/mir24.tv/s/news/16527090/professor-mgu-obyasnil-pochemu-svmda-stanovitsya-centrom-prinyatiya-reshenii', 1]